# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('herido', models.CharField(max_length=2)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.Persona')),
            ],
        ),
    ]
