# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 21, 29, 30, 629074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Persona.Persona'),
        ),
    ]
