# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0002_auto_20171021_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 21, 33, 35, 990788, tzinfo=utc)),
        ),
    ]
