# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0003_auto_20171021_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='lugar',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='comuna',
            field=models.CharField(choices=[('CE', ' Cerrillos'), ('CO', 'Conchalí'), ('EB', 'El Bosque'), ('EC', 'Estación Central'), ('LB', 'Lo Barnechea'), ('LC', 'Las Condes'), ('LF', 'La Florida'), ('MA', 'Maipú'), ('PA', 'Puente Alto'), ('PR', 'Providencia'), ('PE', 'Peñalolén'), ('SA', 'Santiago'), ('SB', 'San Bernardo'), ('SJ', 'San Joaquín'), ('RE', 'Renca'), ('QU', 'Quilicura'), ('VI', 'Vitacura')], default='SA', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='color',
            field=models.CharField(choices=[('A', 'Amarillo'), ('C', 'Cafe'), ('N', 'Naranjo'), ('NE', 'Negro'), ('GR', 'Gris'), ('BL', 'Blanco')], max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='herido',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='sexo',
            field=models.CharField(choices=[('F', 'Hembra'), ('M', 'Macho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('PE', 'Perro'), ('GA', 'Gato'), ('AV', 'Ave'), ('EQ', 'Equino'), ('CE', 'Cerdo'), ('CO', 'Conejo'), ('RO', 'Roedor'), ('BO', 'Bovino')], max_length=50),
        ),
    ]
