# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0004_auto_20171021_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('RE', 'Reportado'), ('CON', 'Consolidado'), ('VE', 'Verificadas'), ('DE', 'Desechadas')], default='RE', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='herido',
            field=models.CharField(choices=[('Abandono', 'Abandono en la Calle'), ('Exposición', 'Exposición a Temperaturas Extremas'), ('FA', 'Falta de Agua'), ('FC', 'Falta de Comida'), ('V', 'Violencia'), ('VA', 'Venta Ambulante')], max_length=50),
        ),
    ]
