# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0007_merge_20171023_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('RE', 'Reportado'), ('CO', 'Consolidado'), ('VE', 'Verificado'), ('CE', 'Cerrado'), ('DE', 'Desechado')], default='RE', max_length=50),
        ),
    ]
