# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_merge_20171023_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
