# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipalidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalidad',
            old_name='ubicacion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='municipalidad',
            name='comuna',
            field=models.CharField(choices=[('CE', ' Cerrillos'), ('CO', 'Conchalí'), ('EB', 'El Bosque'), ('EC', 'Estación Central'), ('LB', 'Lo Barnechea'), ('LC', 'Las Condes'), ('LF', 'La Florida'), ('MA', 'Maipú'), ('PA', 'Puente Alto'), ('PR', 'Providencia'), ('PE', 'Peñalolén'), ('SA', 'Santiago'), ('SB', 'San Bernardo'), ('SJ', 'San Joaquín'), ('RE', 'Renca'), ('QU', 'Quilicura'), ('VI', 'Vitacura')], default='SA', max_length=50),
            preserve_default=False,
        ),
    ]
