# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipalidad', '0002_auto_20171021_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalidad',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
