# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Municipalidad', '0004_merge_20171023_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalidad',
            old_name='usuario',
            new_name='administrador',
        ),
    ]
