# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
