# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0002_auto_20171023_1504'),
        ('ONG', '0002_auto_20171023_1240'),
    ]

    operations = [
    ]
