# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0003_merge_20171023_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ong',
            old_name='usuario',
            new_name='administrador',
        ),
    ]
